apiVersion: v1
kind: Service
metadata:
  name: week1-api-service
  namespace: default
spec:
  selector:
    app: week1-api
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3000        
  type: ClusterIP           