apiVersion: v1
kind: Service
metadata:
  name: week1-frontend-service
  namespace: default
spec:
  selector:
    app: week1-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP